name: generate animation

on:
    # schedule:
    #     - cron: "0 */8 * * *"
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    generate:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Generate GitHub contribution grid snake.svg
              uses: Platane/snk/svg-only@v2
              with:
                  github_user_name: EsinShadrach
                  outputs: |
                      dist/github-contribution-grid-snake.svg
                      dist/github-contribution-grid-snake-dark.svg?palette=github-dark

            - name: Push SVG files to master branch
              uses: crazy-max/ghaction-github-pages@v2.6.0
              with:
                  target_branch: master
                  build_dir: dist
                  keep_history: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
